name: CI
on:
  push:
    branches: [release]

env:
  HUSKY: 0
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install

      - name: Add Git Config
        run: |
          git config user.name "Potter"
          git config user.email "aa4790139@gmail.com"

      - name: Generate Changelog and Create Release
        run: |
          npx changelogen gh release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} 

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          pnpm publish
