name: CI
on:
  push:
    branches: [master]

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  HUSKY: 0
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: master
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install modules
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Add Git Config
        run: |
          git config user.name "Potter"
          git config user.email "aa4790139@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/yxw007/artipub.git

      - name: Check if the latest commit is tagged
        id: check-tag
        run: |
          if output=$(git name-rev --name-only --tags --no-undefined HEAD 2>/dev/null | sed -n "s/^\([^~^]\{1,\}\)\(\^0\)\{0,1\}$/\1/p"); then
            if [ -z "$output" ]; then
              echo "skip=false" >> $GITHUB_ENV
            else
              echo "skip=true" >> $GITHUB_ENV
            fi
          fi

      - name: Echo skip variable
        run: |
          echo "Skip is ${{ env.skip }}"
          echo "Skip is ${{ env.skip }} == 'false'"
          echo "Skip is ${{ env.skip }} == 'true'"

      - name: Generate Changelog and Create Release
        if: env.skip == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          pnpm release --no-git-checks

      - name: Commit changes
        if: env.skip == 'false'
        run: |
          git diff --quiet || git commit -am "chore: auto update for release"

      - uses: ad-m/github-push-action@v0.6.0
        if: env.skip == 'false'
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master

      - name: Set npmrc
        if: env.skip == 'false'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          echo "@pup007:registry=https://registry.npmjs.org" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      - uses: actions/setup-node@v4
        if: env.skip == 'false'
        with:
          node-version: '20.x'
          # Note: Registration-url must be set here, otherwise the permissions will be wrong
          registry-url: 'https://registry.npmjs.org'
          scope: '@pup007'

      - name: Publish package
        if: env.skip == 'false'
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
