name: CI
on:
  push:
    branches: [release]

env:
  HUSKY: 0
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: release
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install

      - name: Add Git Config
        run: |
          git config user.name "Potter"
          git config user.email "aa4790139@gmail.com"

      - name: Generate Changelog and Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} 
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          npx changelogen --release --publish

      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN }} 
          branch: master
